### PR TITLE
All config in on place

### PR DESCRIPTION
**Pull request by mircealungu**
@alinbalutoiu I need your eagle-eyes to check that I'm not missing something critical here. 

Basic idea is that it would be wonderful to have all the configuration files in one place as opposed to having to hunt them across projects. Moreover, the expected config files should actually be ignored by .git so there's no danger of them being committed. 

at some later point we might consider adding even the apache configs to the same folder.

### CODE REVIEW

**Comment by alinbalutoiu** [comment]
Shouldn't this be changed for the ``zeeguu-api-core`` as well? https://github.com/zeeguu-ecosystem/Lineup/blob/master/docker-files/zeeguu-api-core/Dockerfile#L64-L65
Also this should be updated as well: https://github.com/zeeguu-ecosystem/Lineup/blob/master/docker-files-dev/zeeguu-web/Dockerfile#L73-L78
Looks good otherwise.

**Comment by mircealungu** [comment]
Thanks for spotting it @alinbalutoiu ! 
for some reason that file was  `--assume-unchanged` so the changes were not pushed :(

**Comment by mircealungu** [comment]
fixed in: 2b99d11b221deaefacf931cd560febd4ef843948. 
the Dockerfile in zeeguu-web was already modified but you were looking at the one on the master branch.

**Comment by mircealungu** [comment]
Ah, the reason is that the Dockerfile would normally have the FMD related code commented out, and when I uncommented it I decided to not push those changes to the repo. However, from today on I'll assume --assume-unchanged to be an anti-pattern.

**Pull request merged**
